### ISSUE TITLE
Silk Touch II does not save Shulker Box contents

### ISSUE THREAD

**Issue by Amars95** [Viola-Siemens/Advanced-Enchantments#1]

**Comment by Viola-Siemens** [comment]
if needed, edit advanced_enchantments-common-config.toml in 'config' folder, and set SILK_TOUCH_WITH_NBT to true.

**Comment by Amars95** [comment]
Ah it works now, but that should definitely be enabled by default. Thanks for the help!

**Comment by Amars95** [comment]
Any chance the "(+NBT)" text could be removed when using this, though? Kinda pointless since advanced tooltips exist.

**Comment by Viola-Siemens** [comment]
ok, nice advice

**Comment by Amars95** [comment]
Glad I could help, the mod is small but all of the addons are pretty good ones, thanks for this and keep up the good work ^^
